language: elixir

elixir:
  - 1.5.1

addons:
  postgresql: '9.4'

env:
  - MIX_ENV=test

services:
  - postgresql

before_script:
  - mix ecto.drop -r Query.Ecto.Repo
  - mix ecto.create -r Query.Ecto.Repo
  - mix ecto.migrate -r Query.Ecto.Repo

script:
  - mix test
